# Site settings
title: Matthew Gidden's Blog
email: matthew.gidden _at_ gmail.com
description: "You know, a blog."
baseurl: "/blog"
url: "http://mattgidden.com"

# Build settings
markdown: kramdown
permalink: pretty
